<?php
declare(strict_types=1);

// CollegeRoi SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

CollegeRoiUtility::setRegistrar(function (CollegeRoiUtility $u): void {
    $u->clean = [CollegeRoiClean::class, 'call'];
    $u->done = [CollegeRoiDone::class, 'call'];
    $u->make_error = [CollegeRoiMakeError::class, 'call'];
    $u->feature_add = [CollegeRoiFeatureAdd::class, 'call'];
    $u->feature_hook = [CollegeRoiFeatureHook::class, 'call'];
    $u->feature_init = [CollegeRoiFeatureInit::class, 'call'];
    $u->fetcher = [CollegeRoiFetcher::class, 'call'];
    $u->make_fetch_def = [CollegeRoiMakeFetchDef::class, 'call'];
    $u->make_context = [CollegeRoiMakeContext::class, 'call'];
    $u->make_options = [CollegeRoiMakeOptions::class, 'call'];
    $u->make_request = [CollegeRoiMakeRequest::class, 'call'];
    $u->make_response = [CollegeRoiMakeResponse::class, 'call'];
    $u->make_result = [CollegeRoiMakeResult::class, 'call'];
    $u->make_point = [CollegeRoiMakePoint::class, 'call'];
    $u->make_spec = [CollegeRoiMakeSpec::class, 'call'];
    $u->make_url = [CollegeRoiMakeUrl::class, 'call'];
    $u->param = [CollegeRoiParam::class, 'call'];
    $u->prepare_auth = [CollegeRoiPrepareAuth::class, 'call'];
    $u->prepare_body = [CollegeRoiPrepareBody::class, 'call'];
    $u->prepare_headers = [CollegeRoiPrepareHeaders::class, 'call'];
    $u->prepare_method = [CollegeRoiPrepareMethod::class, 'call'];
    $u->prepare_params = [CollegeRoiPrepareParams::class, 'call'];
    $u->prepare_path = [CollegeRoiPreparePath::class, 'call'];
    $u->prepare_query = [CollegeRoiPrepareQuery::class, 'call'];
    $u->graphql_body = [CollegeRoiGraphql::class, 'body'];
    $u->graphql_errors = [CollegeRoiGraphql::class, 'errors'];
    $u->result_basic = [CollegeRoiResultBasic::class, 'call'];
    $u->result_body = [CollegeRoiResultBody::class, 'call'];
    $u->result_headers = [CollegeRoiResultHeaders::class, 'call'];
    $u->transform_request = [CollegeRoiTransformRequest::class, 'call'];
    $u->transform_response = [CollegeRoiTransformResponse::class, 'call'];
});
